django_app/diary/urls.py
from django.conf.urls import url

from diary import views

urlpatterns = [
    url(r'^add/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.diary_add, name='diary_add'),
    url(r'^calendar/month/$', views.month_calendar, name='month_calendar'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
        views.diary_detail, name='diary_detail'),
]

django_app/diarySite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^diary/', include('diary.urls', namespace='diary')),
    url(r'^admin/', admin.site.urls),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^index/$', TemplateView.as_view(template_name='index.html'), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

django_app/diary/models.py
from django.db import models

from diarySite.settings import AUTH_USER_MODEL


class Diary(models.Model):
    title = models.CharField(max_length=40)
    content = models.TextField()
    author = models.ForeignKey(AUTH_USER_MODEL)
    diary_date = models.DateField()

    def __str__(self):
        return self.title

django_app/diary/forms.py
from django import forms
from .models import Diary


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'content',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            }

django_app/diary/views/diary_add.py
import datetime

from django.shortcuts import redirect, render

from diary.forms import DiaryForm

__all__ =[
    'diary_add'
]


def diary_add(request, year, month, day):
    user = request.user
    diary_date = datetime.strptime(year+'-'+month+'-'+day, "%Y-%m-%d").date()
    if request.method == 'POST':
        form = DiaryForm(request.POST)
        if form.is_valid():
            diary = form.save(commit=False)
            diary.author = user
            diary.diary_date = diary_date
            diary.save()
            return redirect('diary:diary_detail', year=year, month=month, day=day)
    else:
        form = DiaryForm()
        context = {
            'form': form,
            'year': year,
            'month': month,
            'day': day
        }
        return render(request, 'diary/diary_add.html', context)

django_app/diary/views/diary_detail.py
# python
from datetime import datetime

from django.contrib import messages
from django.shortcuts import render, redirect

from diary.models import Diary

__all__ = [
    'diary_detail',
]


def diary_detail(request, year, month, day):
    selected_date = datetime.strptime(year+month+day, '%Y%m%d').date()
    diary_query = Diary.objects.filter(diary_date=selected_date)
    context = {
        'diary_query': diary_query,
    }
    if diary_query.exists():
        return render(request, 'diary/diary_detail.html', context)
    else:
        messages.info(request, '일기를 작성해 주세요.')
        return redirect('diary:diary_add', year=year, month=month, day=day)

django_app/diary/views/month_calendar.py
import calendar
from datetime import datetime

from django.shortcuts import render

from diary.models import Diary

__all__ = [
    'month_calendar'
]


def month_calendar(request):
    if request.GET.get('pre_calendar'):
        pre_cal = (request.GET.get('pre_calendar')).split('-')
        year = int(pre_cal[0])
        month = int(pre_cal[1])
    elif request.GET.get('next_calendar'):
        next_cal = (request.GET.get('next_calendar')).split('-')
        year = int(next_cal[0])
        month = int(next_cal[1])
    else:
        today = datetime.today()
        year = today.year
        month = today.month

    pre_month = 12 if month-1 < 1 else month - 1
    pre_year = year - 1 if pre_month == 12 else year
    next_month = 1 if month + 1 > 12 else month + 1
    next_year = year + 1 if next_month == 1 else year
    pre_calendar = str(pre_year) + "-" + str(pre_month)
    next_calendar = str(next_year) + "-" + str(next_month)

    this_month_diary = Diary.objects.filter(diary_date__year=year, diary_date__month=month, author=request.user)
    monthdays = calendar.Calendar(calendar.SUNDAY).monthdayscalendar(year, month)
    monthdays = [[('0'+str(day), day) if day < 10 else (str(day), day) for day in week] for week in monthdays]
    context = {
        'monthdays': monthdays,
        'year': year,
        'month': ('{:02d}'.format(month), month),
        'days': ('일', '월', '화', '수', '목', '금', '토',),
        'this_month_diary': this_month_diary,
        'pre_calendar': pre_calendar,
        'next_calendar': next_calendar
    }

    return render(request, 'diary/month_calendar.html', context)

django_app/templates/diary/diary_add.html
{% extends 'common/base.html' %}

{% block content %}
    <h4 class="diary_date">{{ year }}년 {{ month }}월 {{ day }}일</h4>
    <form action=""method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장</button>
    </form>
{% endblock %}

django_app/templates/diary/diary_detail.html
{% extends 'common/base.html' %}
{% block content %}
{% for diary in diary_query %}
    <h3>{{diary.title}}</h3>
    {{diary.content}}
{% endfor %}
{% endblock %}}

django_app/templates/diary/diary_photo.html
{% extends 'common/base.html' %}

{% block content %}
photo
 {% for photo in exampleModel %}
    <img src="{{ photo.image.crop.200x200 }}" alt="">
 {% endfor %}
{% endblock %}

django_app/templates/diary/month_calendar.html
{% extends 'common/base.html' %}

{% block content %}
    <table class="col-xs-offset-1 col-xs-10 custom_table">
    <tr>
        <td><a href="{% url 'diary:month_calendar' %}?pre_calendar={{pre_calendar}}">pre</a></td>
        <th colspan="5">{{ month.1 }}<small class=year>{{ year }}</small></th>
        <td><a href="{% url 'diary:month_calendar' %}?next_calendar={{next_calendar}}">next</a></td>
    </tr>
    <tr>
        {% for day in days %}
            <td class="day">{{ day }}</td>
        {% endfor %}
    </tr>
    {% for week in monthdays %}
     <tr>
        {% for date in week %}
            {% if date.1 != 0 %}
                <td class="date-link">
                    <a href="{% url 'diary:diary_detail' year=year month=month.0 day=date.0 %}">
                        <div id=date{{date.1}} class="link-div">{{ date.1 }}</div>
                    </a>
                </td>
            {% else %}
            <td></td>
            {% endif %}
        {% endfor %}
     </tr>
    {% endfor %}
    </table>

    {% for diary in this_month_diary %}
        <script>diary_check('{{ diary.diary_date.day}}')</script>
    {% endfor %}

{% endblock %}