django_app/diary/urls.py
from django.conf.urls import url

from diary import views

urlpatterns = [
    url(r'^add/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', views.diary_add, name='diary_add'),
    url(r'^calendar/month/$', views.month_calendar, name='month_calendar'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
        views.diary_detail, name='diary_detail'),
]

django_app/diarySite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^diary/', include('diary.urls', namespace='diary')),
    url(r'^admin/', admin.site.urls),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^index/$', TemplateView.as_view(template_name='index.html'), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

django_app/member/urls.py
from django.conf.urls import url

from member.views import ResetPasswordRequestView, PasswordResetConfirmView, LoginView, logout_view, SignupView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'^reset_psw/$', ResetPasswordRequestView.as_view(), name='reset_psw'),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
]

django_app/templates/index.html
{% extends 'common/member.html' %}
{% block member_content %}
    <a href="{% url 'member:signup' %}"><div id=signup class="main-btn">회원가입</div></a>
    <a href="{% url 'member:login' %}"><div id="login" class="main-btn">로그인</div></a>
    <a id="facebook-login" class="social-btn col-md-6" href="{% url 'social:begin' 'facebook' %}">FACEBOOK</a>
    <a id="google-login" class="social-btn col-md-6"  href="{% url 'social:begin' 'google-oauth2' %}">GOOGLE</a>
{% endblock %}